### ISSUE TITLE
Add "Fork me on GitHub" ribbon

### ISSUE THREAD

**Issue by ramaciotti** [flachadriano/releasenotes#3]
Like this: https://github.com/blog/273-github-ribbons

**Comment by flachadriano** [comment]
Fixed into commit: https://github.com/flachadriano/releasenotes/commit/f3a231c32de8422e88cadd51b9b793f214b9ed1e

**Comment by flachadriano** [comment]
Fixed into the commit: https://github.com/flachadriano/releasenotes/commit/484c75d55c088292cddd35b9bea6aea451ad2392
